---
- hosts: all
  become: yes
  tasks:
        - name: I want to install tree software
          apt:
               name: tree
               state: present

- hosts: all
  become: yes
  tasks:
        - name: I want to install wget software
          apt:
               name: wget
               state: present               