---
- hosts: all
  become: yes
  tasks:
        - name: I want to install web server on ubuntu node
          apt:
               name: apache2
               state: absent


        - name: I want to start web server on ubuntu node
          service:
                   name: apache2
                   state: stopped

 
        - name: I want to check ansible os family    
          service:
                   name: apache2
                   state: stopped 
          when: ansible_os_family== "Debian"


        - name: I want to install webserver on redhat node
          yum:
                   name: httpd
                   state: present 
          when: ansible_os_family== "RedHat"


        - name: I want to start webserver on redhat node
          service:
                   name: httpd
                   state: started 
          when: ansible_os_family== "RedHat"