---
- hosts: all
  become: yes
  tasks:
        - name: I want to install web server on ubuntu node
          apt:
               name: apache2
               state: present

- hosts: all
  become: yes
  tasks:
        - name: I want to start web server on ubuntu node
          service:
                   name: apache2
                   state: started

- hosts: all
  become: yes                    
  tasks:                 
        - name: I want to check ansible os family    
          service:
                   name: apache2
                   state: started 
          when: ansible_os_family== "Debian"
        